[package]
name = "dht11"
version = "0.1.0"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
description = "A driver for DHT11 temperature and humidity sensor"

[dependencies]
# cupi = { git = "https://github.com/inre/cupi" }
cupi = "0.1.0"
